import { Config, MerchantMapping } from '../config/types.js';

export function generateConfigTemplate(merchants: string[]): string {
  const sorted = [...merchants].sort((a, b) =>
    a.toLowerCase().localeCompare(b.toLowerCase())
  );

  const lines: string[] = [
    '# Generated by csv-to-txf init',
    '# Fill in the \'organization\' field for each merchant',
    'mappings:',
  ];

  for (const merchant of sorted) {
    lines.push(`  - merchant: "${merchant}"`);
    lines.push('    organization: ""  # TODO: Fill in official organization name');
    lines.push('    # ein: ""  # Optional: Add EIN');
    lines.push('');
  }

  return lines.join('\n');
}

export function mergeConfigs(existing: Config, newMerchants: string[]): Config {
  // Create a map of existing mappings by lowercase merchant name
  const existingMap = new Map<string, MerchantMapping>();
  for (const mapping of existing.mappings) {
    existingMap.set(mapping.merchant.toLowerCase(), mapping);
  }

  // Process new merchants
  const resultMap = new Map<string, MerchantMapping>();

  // First, add all existing mappings
  for (const mapping of existing.mappings) {
    resultMap.set(mapping.merchant.toLowerCase(), mapping);
  }

  // Then add new merchants that don't exist
  for (const merchant of newMerchants) {
    const key = merchant.toLowerCase();
    if (!resultMap.has(key)) {
      resultMap.set(key, {
        merchant,
        organization: '',
      });
    }
  }

  // Convert to array and sort
  const mappings = Array.from(resultMap.values());
  mappings.sort((a, b) =>
    a.merchant.toLowerCase().localeCompare(b.merchant.toLowerCase())
  );

  return { mappings };
}

export function generateMergedConfigYaml(config: Config): string {
  const lines: string[] = [
    '# Generated by csv-to-txf init --merge',
    '# Existing mappings preserved, new merchants added',
    'mappings:',
  ];

  for (const mapping of config.mappings) {
    lines.push(`  - merchant: "${mapping.merchant}"`);

    if (mapping.organization) {
      lines.push(`    organization: "${mapping.organization}"`);
    } else {
      lines.push('    organization: ""  # TODO: Fill in official organization name');
    }

    if (mapping.ein) {
      lines.push(`    ein: "${mapping.ein}"`);
    } else {
      lines.push('    # ein: ""  # Optional: Add EIN');
    }

    lines.push('');
  }

  return lines.join('\n');
}
