import { describe, it, expect } from 'vitest';
import { generateConfigTemplate, mergeConfigs, generateMergedConfigYaml } from '../../src/cli/init.js';
import { parseCSV } from '../../src/csv/parser.js';
import { extractUniqueMerchants } from '../../src/merchant/extractor.js';
import { loadConfig } from '../../src/config/loader.js';
import path from 'path';

const fixturesPath = path.resolve(__dirname, '../fixtures');

describe('Init Command Integration', () => {
  it('should extract merchants from CSV and generate template', async () => {
    const rows = await parseCSV(path.join(fixturesPath, 'csv/valid.csv'));
    const merchants = extractUniqueMerchants(rows);
    const template = generateConfigTemplate(merchants);

    expect(template).toContain('# Generated by csv-to-txf init');
    expect(template).toContain('mappings:');
    expect(template).toContain('GOODWILL DONATION');
    expect(template).toContain('RED CROSS');
    expect(template).toContain('UNITED WAY');
  });

  it('should merge with existing config', async () => {
    const existingConfig = await loadConfig(path.join(fixturesPath, 'config/valid.yaml'));
    const newMerchants = ['RED CROSS', 'NEW CHARITY'];

    const merged = mergeConfigs(existingConfig, newMerchants);

    // Should preserve existing organization names
    const redCross = merged.mappings.find(m =>
      m.merchant.toLowerCase() === 'red cross'
    );
    expect(redCross?.organization).toBe('American National Red Cross');
    expect(redCross?.ein).toBe('53-0196605');

    // Should add new merchant with empty organization
    const newCharity = merged.mappings.find(m =>
      m.merchant.toLowerCase() === 'new charity'
    );
    expect(newCharity?.merchant).toBe('NEW CHARITY');
    expect(newCharity?.organization).toBe('');
  });

  it('should generate valid YAML from merged config', async () => {
    const existingConfig = await loadConfig(path.join(fixturesPath, 'config/valid.yaml'));
    const newMerchants = ['RED CROSS', 'NEW CHARITY'];

    const merged = mergeConfigs(existingConfig, newMerchants);
    const yaml = generateMergedConfigYaml(merged);

    expect(yaml).toContain('# Generated by csv-to-txf init --merge');
    expect(yaml).toContain('mappings:');
    expect(yaml).toContain('American National Red Cross');
    expect(yaml).toContain('NEW CHARITY');
  });

  it('should sort merchants alphabetically', async () => {
    const rows = await parseCSV(path.join(fixturesPath, 'csv/valid.csv'));
    const merchants = extractUniqueMerchants(rows);

    // Should be sorted: GOODWILL, RED CROSS, UNITED WAY
    expect(merchants[0]).toBe('GOODWILL DONATION');
    expect(merchants[1]).toBe('RED CROSS');
    expect(merchants[2]).toBe('UNITED WAY');
  });

  it('should handle empty CSV', async () => {
    const rows = await parseCSV(path.join(fixturesPath, 'csv/empty.csv'));
    const merchants = extractUniqueMerchants(rows);

    expect(merchants).toHaveLength(0);

    const template = generateConfigTemplate(merchants);
    expect(template).toContain('mappings:');
  });

  it('should deduplicate merchants case-insensitively', async () => {
    // Create test with duplicate merchants different cases
    const merchants = extractUniqueMerchants([
      { merchant: 'Red Cross', date: '', category: '', account: '', originalStatement: '', notes: '', amount: '', tags: '', owner: '', lineNumber: 1 },
      { merchant: 'RED CROSS', date: '', category: '', account: '', originalStatement: '', notes: '', amount: '', tags: '', owner: '', lineNumber: 2 },
    ]);

    expect(merchants).toHaveLength(1);
    expect(merchants[0]).toBe('Red Cross'); // First occurrence preserved
  });
});
