import { describe, it, expect } from 'vitest';
import { generateConfigTemplate, mergeConfigs } from '../../../src/cli/init.js';
import { Config } from '../../../src/config/types.js';

describe('InitCommand', () => {
  describe('generateConfigTemplate', () => {
    it('should generate YAML with all unique merchants', () => {
      const merchants = ['RED CROSS', 'UNITED WAY'];
      const yaml = generateConfigTemplate(merchants);
      expect(yaml).toContain('merchant: "RED CROSS"');
      expect(yaml).toContain('merchant: "UNITED WAY"');
    });

    it('should include placeholder organization fields', () => {
      const yaml = generateConfigTemplate(['TEST']);
      expect(yaml).toContain('organization: ""');
      expect(yaml).toContain('# TODO');
    });

    it('should include commented EIN field', () => {
      const yaml = generateConfigTemplate(['TEST']);
      expect(yaml).toContain('# ein:');
    });

    it('should include header comment', () => {
      const yaml = generateConfigTemplate(['TEST']);
      expect(yaml).toContain('# Generated by csv-to-txf init');
    });

    it('should sort merchants alphabetically', () => {
      const yaml = generateConfigTemplate(['ZEBRA', 'ALPHA', 'MIDDLE']);
      const alphaIndex = yaml.indexOf('ALPHA');
      const middleIndex = yaml.indexOf('MIDDLE');
      const zebraIndex = yaml.indexOf('ZEBRA');
      expect(alphaIndex).toBeLessThan(middleIndex);
      expect(middleIndex).toBeLessThan(zebraIndex);
    });

    it('should handle empty merchants list', () => {
      const yaml = generateConfigTemplate([]);
      expect(yaml).toContain('mappings:');
    });

    it('should escape quotes in merchant names', () => {
      const yaml = generateConfigTemplate(["O'BRIEN'S CHARITY"]);
      expect(yaml).toContain("O'BRIEN'S CHARITY");
    });
  });

  describe('mergeConfigs', () => {
    it('should preserve existing mappings', () => {
      const existing: Config = {
        mappings: [
          { merchant: 'RED CROSS', organization: 'American Red Cross', ein: '53-0196605' }
        ]
      };
      const newMerchants = ['RED CROSS', 'UNITED WAY'];
      const result = mergeConfigs(existing, newMerchants);

      const redCross = result.mappings.find(m => m.merchant.toUpperCase() === 'RED CROSS');
      expect(redCross?.organization).toBe('American Red Cross');
      expect(redCross?.ein).toBe('53-0196605');
    });

    it('should add new merchants with empty organization', () => {
      const existing: Config = {
        mappings: [{ merchant: 'RED CROSS', organization: 'American Red Cross' }]
      };
      const newMerchants = ['RED CROSS', 'UNITED WAY'];
      const result = mergeConfigs(existing, newMerchants);

      const unitedWay = result.mappings.find(m => m.merchant.toUpperCase() === 'UNITED WAY');
      expect(unitedWay?.organization).toBe('');
    });

    it('should match existing mappings case-insensitively', () => {
      const existing: Config = {
        mappings: [{ merchant: 'Red Cross', organization: 'American Red Cross' }]
      };
      const newMerchants = ['RED CROSS'];
      const result = mergeConfigs(existing, newMerchants);

      expect(result.mappings).toHaveLength(1);
      expect(result.mappings[0].merchant).toBe('Red Cross');
    });

    it('should sort merged results alphabetically', () => {
      const existing: Config = { mappings: [{ merchant: 'ZEBRA', organization: 'Z Org' }] };
      const newMerchants = ['ALPHA'];
      const result = mergeConfigs(existing, newMerchants);

      expect(result.mappings[0].merchant.toUpperCase()).toBe('ALPHA');
      expect(result.mappings[1].merchant.toUpperCase()).toBe('ZEBRA');
    });

    it('should handle empty existing config', () => {
      const existing: Config = { mappings: [] };
      const newMerchants = ['NEW MERCHANT'];
      const result = mergeConfigs(existing, newMerchants);

      expect(result.mappings).toHaveLength(1);
      expect(result.mappings[0].merchant).toBe('NEW MERCHANT');
    });
  });
});
